name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Criar o resource group (caso não exista)
        run: |
          az group create \
            --name MeuGrupoBicep \
            -- location eastus

      - name: Deploy do Bicep
        run: |
          az deployment group create \
            --resource-group MeuGrupoBicep \
            --template-file main.bicep \
            --parameters adminPassword='${{ secrets.ADMIN_PASSWORD}}'

      - name: Obter IP público da VM
        run : |
          az network public-ip show \
            --resource-group MeuGrupoBicep \
            --name mac-lab-bicep-pip \
            --query ipAddress \
            --output tsv